version: '2.3'

services:
  main:
    container_name: "retrieval_engine_fashion"
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    env_file:
      - "docker-compose-env/main.env"
    volumes:
      - type: volume
        source: nfs_shared
        target: /dataset
        volume:
          nocopy: true
    expose:
      - "8000"
    ports:
      - "38002:8000"
    ipc: host
    stdin_open: true
    tty: true
    depends_on:
      engine_db:
        condition: service_healthy
    links:
      - engine_db


  engine_db:
    container_name: "retrieval_engine_fashion_db"
    image: mysql:8.0.21
    restart: always
    expose:
      - "3306"
    env_file:
      - docker-compose-env/db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume2/nfs_shared/ms/ImageRetrievalDemo/dataset"
